development:
  adapter: postgresql
  encoding: unicode
  database: chartertracker_development
  pool: 5
  username: user
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: chartertracker_test
  pool: 5
  username: user
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: chartertracker_production
  pool: 5
  password:
  host: localhost